version: '2'
services:
    microservice1-app:
        image: microservice1
        external_links:
            - microservice1-mariadb:mariadb
            - microservice1-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/microservice1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    microservice1-mariadb:
        extends:
            file: mariadb.yml
            service: microservice1-mariadb
    microservice1-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: microservice1-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
