version: '2'
services:
    microservice1-mariadb:
        container_name: microservice1-mariadb
        image: mariadb:10.1.16
        # volumes:
        #     - ~/volumes/jhipster/microservice1/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=microservice1
        ports:
            - 3306:3306
