version: '2'
services:
    microservice1-postgresql:
        container_name: microservice1-postgresql
        image: postgres:9.5.3
        # volumes:
        #     - ~/volumes/jhipster/microservice1/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=microservice1
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
